"""Emit concrete Python source for a Databricks App MCP server.

Input: list of internal tool definition dicts (parsed from an OpenAPI spec).
Output: a complete, self-contained ``main.py`` source string.

No file I/O is performed here — callers are responsible for writing the output.
"""

from __future__ import annotations

_TYPE_MAP: dict[str, str] = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "array": "list",
    "object": "dict",
}


def _map_type(openapi_type: str | None) -> str:
    """Map an OpenAPI primitive type string to a Python type hint string."""
    return _TYPE_MAP.get(openapi_type or "", "dict")


def _emit_signature(tool: dict) -> str:
    """Return the ``async def`` line for a tool function."""
    fn_name = tool["name"].replace("-", "_")
    params = tool.get("all_params", [])

    # Sort: required first, optional after
    required = [p for p in params if p.get("required")]
    optional = [p for p in params if not p.get("required")]

    parts: list[str] = []
    for p in required:
        # type is already a Python type string in the internal tool def
        py_type = p.get("type") or "dict"
        parts.append(f"{p['name']}: {py_type}")
    for p in optional:
        py_type = p.get("type") or "dict"
        if py_type == "bool":
            parts.append(f"{p['name']}: {py_type} = False")
        elif py_type in ("int", "float"):
            parts.append(f"{p['name']}: {py_type} = 0")
        else:
            parts.append(f"{p['name']}: {py_type} | None = None")

    args = ", ".join(parts)
    return f"async def {fn_name}({args}) -> str:"


def _emit_path(path: str, path_params: list[str]) -> str:
    """Return a Python expression for the URL path.

    Plain string for no path params; f-string when params are present.
    """
    if not path_params:
        return f'"{path}"'
    return f'f"{path}"'


def _emit_request_call(tool: dict) -> str:
    """Return the ``return _uc_request(...)`` line for a tool handler."""
    method = tool["method"]
    path_params = tool.get("path_params", [])
    query_params = tool.get("query_params", [])
    body_params = tool.get("body_params", [])

    path_expr = _emit_path(tool["path"], path_params)

    kwargs: list[str] = []

    if query_params:
        items = ", ".join(f'"{p}": {p}' for p in query_params)
        kwargs.append(f"query_params={{{items}}}")

    if body_params and method != "GET":
        items = ", ".join(f'"{p["name"]}": {p["name"]}' for p in body_params)
        kwargs.append(f"body={{{items}}}")

    call = f'return _uc_request("{method}", {path_expr}'
    if kwargs:
        call += ", " + ", ".join(kwargs)
    call += ")"
    return call


def _emit_tool_function(tool: dict) -> str:
    """Return the complete decorated function source for one tool."""
    fn_name = tool["name"].replace("-", "_")
    description = tool.get("description") or ""
    sig = _emit_signature(tool)
    request_call = _emit_request_call(tool)

    lines: list[str] = [
        "@mcp.tool()",
        sig,
    ]
    if description:
        lines.append(f'    """{description}"""')
    lines.append(f"    {request_call}")

    return "\n".join(lines) + "\n\n"


def _emit_header(service_name: str, connection_name: str, spec_source: str) -> str:
    """Return the top-of-file header and imports."""
    return f'''\
# Generated by uc-mcp generate
# Spec: {spec_source}
# Connection: {connection_name}

from __future__ import annotations

import contextvars
import json
import logging
import os
from typing import Optional

import uvicorn
from databricks.sdk import WorkspaceClient
from databricks.sdk.credentials_provider import ModelServingUserCredentials
from databricks.sdk.service.serving import ExternalFunctionRequestHttpMethod
from mcp.server.fastmcp import FastMCP
from mcp.server.streamable_http_manager import StreamableHTTPSessionManager
from starlette.applications import Starlette
from starlette.routing import Mount
import contextlib

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

mcp = FastMCP("{service_name}")
CONNECTION_NAME = "{connection_name}"

'''


def _emit_uc_request_helper() -> str:
    """Return the inlined ``_uc_request`` HTTP proxy helper."""
    return '''\
_METHOD_MAP = {
    "GET": ExternalFunctionRequestHttpMethod.GET,
    "POST": ExternalFunctionRequestHttpMethod.POST,
    "PUT": ExternalFunctionRequestHttpMethod.PUT,
    "PATCH": ExternalFunctionRequestHttpMethod.PATCH,
    "DELETE": ExternalFunctionRequestHttpMethod.DELETE,
}


def _uc_request(
    method: str,
    path: str,
    *,
    body: dict | None = None,
    query_params: dict | None = None,
    _client: WorkspaceClient | None = None,
) -> str:
    client = _client or _get_workspace_client()
    resp = client.serving_endpoints.http_request(
        conn=CONNECTION_NAME,
        method=_METHOD_MAP[method],
        path=path,
        headers={},
        json=body or {},
        params=query_params or {},
    )
    return resp.text if hasattr(resp, "text") else str(resp)


'''


def _emit_middleware() -> str:
    """Return per-user auth middleware and Starlette app setup."""
    return '''\
# ── Per-user auth ─────────────────────────────────────────────────────────

_forwarded_token: contextvars.ContextVar[Optional[str]] = contextvars.ContextVar(
    "_forwarded_token", default=None
)


class _ForwardedTokenMiddleware:
    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] == "http":
            headers = dict(scope.get("headers", []))
            token = (headers.get(b"x-forwarded-access-token") or b"").decode() or None
            _forwarded_token.set(token)
        await self.app(scope, receive, send)


def _get_workspace_client() -> WorkspaceClient:
    token = _forwarded_token.get()
    if token:
        return WorkspaceClient(token=token, auth_type="pat")
    if os.environ.get("IS_IN_DATABRICKS_MODEL_SERVING_ENV"):
        return WorkspaceClient(credentials_strategy=ModelServingUserCredentials())
    return WorkspaceClient()


# ── Starlette app ─────────────────────────────────────────────────────────


def _create_app() -> Starlette:
    session_manager = StreamableHTTPSessionManager(
        app=mcp._mcp_server,
        stateless=True,
        json_response=True,
    )

    @contextlib.asynccontextmanager
    async def lifespan(app: Starlette):
        async with session_manager.run():
            yield

    app = Starlette(
        routes=[Mount("/mcp", app=session_manager.handle_request)],
        lifespan=lifespan,
    )
    return _ForwardedTokenMiddleware(app)


'''


def _emit_entrypoint() -> str:
    """Return the ``if __name__ == "__main__"`` entrypoint block."""
    return '''\
if __name__ == "__main__":
    uvicorn.run(_create_app(), host="0.0.0.0", port=8000)
'''


def emit_module(
    tools: list[dict],
    connection_name: str,
    service_name: str,
    spec_source: str,
) -> str:
    """Return the full main.py source as a string.

    Args:
        tools: List of internal tool definition dicts.
        connection_name: Databricks UC connection name.
        service_name: MCP service name (used in FastMCP instantiation).
        spec_source: Path or URL of the OpenAPI spec (for the header comment).

    Returns:
        Complete Python source string for main.py.
    """
    parts: list[str] = [
        _emit_header(service_name, connection_name, spec_source),
        _emit_uc_request_helper(),
        _emit_middleware(),
    ]

    for tool in tools:
        parts.append(_emit_tool_function(tool))

    parts.append(_emit_entrypoint())
    return "".join(parts)
