# Generated by uc-mcp generate
# Spec: https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json
# Connection: slack

from __future__ import annotations

import contextvars
import json
import logging
import os
from typing import Optional

import uvicorn
from databricks.sdk import WorkspaceClient
from databricks.sdk.credentials_provider import ModelServingUserCredentials
from databricks.sdk.service.serving import ExternalFunctionRequestHttpMethod
from mcp.server.fastmcp import FastMCP
from mcp.server.streamable_http_manager import StreamableHTTPSessionManager
from starlette.applications import Starlette
from starlette.routing import Mount
import contextlib

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

mcp = FastMCP("slack")
CONNECTION_NAME = "slack"

_METHOD_MAP = {
    "GET": ExternalFunctionRequestHttpMethod.GET,
    "POST": ExternalFunctionRequestHttpMethod.POST,
    "PUT": ExternalFunctionRequestHttpMethod.PUT,
    "PATCH": ExternalFunctionRequestHttpMethod.PATCH,
    "DELETE": ExternalFunctionRequestHttpMethod.DELETE,
}


def _uc_request(
    method: str,
    path: str,
    *,
    body: dict | None = None,
    query_params: dict | None = None,
    _client: WorkspaceClient | None = None,
) -> str:
    client = _client or _get_workspace_client()
    resp = client.serving_endpoints.http_request(
        conn=CONNECTION_NAME,
        method=_METHOD_MAP[method],
        path=path,
        headers={},
        json=body or {},
        params=query_params or {},
    )
    return resp.text if hasattr(resp, "text") else str(resp)


# ── Per-user auth ─────────────────────────────────────────────────────────

_forwarded_token: contextvars.ContextVar[Optional[str]] = contextvars.ContextVar(
    "_forwarded_token", default=None
)


class _ForwardedTokenMiddleware:
    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] == "http":
            headers = dict(scope.get("headers", []))
            token = (headers.get(b"x-forwarded-access-token") or b"").decode() or None
            _forwarded_token.set(token)
        await self.app(scope, receive, send)


def _get_workspace_client() -> WorkspaceClient:
    token = _forwarded_token.get()
    if token:
        return WorkspaceClient(token=token, auth_type="pat")
    if os.environ.get("IS_IN_DATABRICKS_MODEL_SERVING_ENV"):
        return WorkspaceClient(credentials_strategy=ModelServingUserCredentials())
    return WorkspaceClient()


# ── Starlette app ─────────────────────────────────────────────────────────


def _create_app() -> Starlette:
    session_manager = StreamableHTTPSessionManager(
        app=mcp._mcp_server,
        stateless=True,
        json_response=True,
    )

    @contextlib.asynccontextmanager
    async def lifespan(app: Starlette):
        async with session_manager.run():
            yield

    app = Starlette(
        routes=[Mount("/mcp", app=session_manager.handle_request)],
        lifespan=lifespan,
    )
    return _ForwardedTokenMiddleware(app)


@mcp.tool()
async def admin_apps_approve(token: dict, app_id: dict | None = None, request_id: dict | None = None, team_id: dict | None = None) -> str:
    """Approve an app for installation on a workspace."""
    return _uc_request("POST", "/admin.apps.approve")

@mcp.tool()
async def admin_apps_approved_list(token: dict, limit: dict | None = None, cursor: dict | None = None, team_id: dict | None = None, enterprise_id: dict | None = None) -> str:
    """List approved apps for an org or workspace."""
    return _uc_request("GET", "/admin.apps.approved.list", query_params={"token": token, "limit": limit, "cursor": cursor, "team_id": team_id, "enterprise_id": enterprise_id})

@mcp.tool()
async def admin_apps_requests_list(token: dict, limit: dict | None = None, cursor: dict | None = None, team_id: dict | None = None) -> str:
    """List app requests for a team/workspace."""
    return _uc_request("GET", "/admin.apps.requests.list", query_params={"token": token, "limit": limit, "cursor": cursor, "team_id": team_id})

@mcp.tool()
async def admin_apps_restrict(token: dict, app_id: dict | None = None, request_id: dict | None = None, team_id: dict | None = None) -> str:
    """Restrict an app for installation on a workspace."""
    return _uc_request("POST", "/admin.apps.restrict")

@mcp.tool()
async def admin_apps_restricted_list(token: dict, limit: dict | None = None, cursor: dict | None = None, team_id: dict | None = None, enterprise_id: dict | None = None) -> str:
    """List restricted apps for an org or workspace."""
    return _uc_request("GET", "/admin.apps.restricted.list", query_params={"token": token, "limit": limit, "cursor": cursor, "team_id": team_id, "enterprise_id": enterprise_id})

@mcp.tool()
async def admin_conversations_archive(token: dict, channel_id: dict) -> str:
    """Archive a public or private channel."""
    return _uc_request("POST", "/admin.conversations.archive")

@mcp.tool()
async def admin_conversations_converttoprivate(token: dict, channel_id: dict) -> str:
    """Convert a public channel to a private channel."""
    return _uc_request("POST", "/admin.conversations.convertToPrivate")

@mcp.tool()
async def admin_conversations_create(token: dict, name: dict, is_private: dict, description: dict | None = None, org_wide: dict | None = None, team_id: dict | None = None) -> str:
    """Create a public or private channel-based conversation."""
    return _uc_request("POST", "/admin.conversations.create")

@mcp.tool()
async def admin_conversations_delete(token: dict, channel_id: dict) -> str:
    """Delete a public or private channel."""
    return _uc_request("POST", "/admin.conversations.delete")

@mcp.tool()
async def admin_conversations_disconnectshared(token: dict, channel_id: dict, leaving_team_ids: dict | None = None) -> str:
    """Disconnect a connected channel from one or more workspaces."""
    return _uc_request("POST", "/admin.conversations.disconnectShared")

@mcp.tool()
async def admin_conversations_ekm_listoriginalconnectedchannelinfo(token: dict, channel_ids: dict | None = None, team_ids: dict | None = None, limit: dict | None = None, cursor: dict | None = None) -> str:
    """List all disconnected channels—i.e., channels that were once connected to other workspaces and then disconnected—and the corresponding original channel IDs for key revocation with EKM."""
    return _uc_request("GET", "/admin.conversations.ekm.listOriginalConnectedChannelInfo", query_params={"token": token, "channel_ids": channel_ids, "team_ids": team_ids, "limit": limit, "cursor": cursor})

@mcp.tool()
async def admin_conversations_getconversationprefs(token: dict, channel_id: dict) -> str:
    """Get conversation preferences for a public or private channel."""
    return _uc_request("GET", "/admin.conversations.getConversationPrefs", query_params={"channel_id": channel_id})

@mcp.tool()
async def admin_conversations_getteams(token: dict, channel_id: dict, cursor: dict | None = None, limit: dict | None = None) -> str:
    """Get all the workspaces a given public or private channel is connected to within this Enterprise org."""
    return _uc_request("GET", "/admin.conversations.getTeams", query_params={"channel_id": channel_id, "cursor": cursor, "limit": limit})

@mcp.tool()
async def admin_conversations_invite(token: dict, user_ids: dict, channel_id: dict) -> str:
    """Invite a user to a public or private channel."""
    return _uc_request("POST", "/admin.conversations.invite")

@mcp.tool()
async def admin_conversations_rename(token: dict, channel_id: dict, name: dict) -> str:
    """Rename a public or private channel."""
    return _uc_request("POST", "/admin.conversations.rename")

@mcp.tool()
async def admin_conversations_restrictaccess_addgroup(token: dict, group_id: dict, channel_id: dict, team_id: dict | None = None) -> str:
    """Add an allowlist of IDP groups for accessing a channel"""
    return _uc_request("POST", "/admin.conversations.restrictAccess.addGroup")

@mcp.tool()
async def admin_conversations_restrictaccess_listgroups(token: dict, channel_id: dict, team_id: dict | None = None) -> str:
    """List all IDP Groups linked to a channel"""
    return _uc_request("GET", "/admin.conversations.restrictAccess.listGroups", query_params={"token": token, "channel_id": channel_id, "team_id": team_id})

@mcp.tool()
async def admin_conversations_restrictaccess_removegroup(token: dict, team_id: dict, group_id: dict, channel_id: dict) -> str:
    """Remove a linked IDP group linked from a private channel"""
    return _uc_request("POST", "/admin.conversations.restrictAccess.removeGroup")

@mcp.tool()
async def admin_conversations_search(token: dict, team_ids: dict | None = None, query: dict | None = None, limit: dict | None = None, cursor: dict | None = None, search_channel_types: dict | None = None, sort: dict | None = None, sort_dir: dict | None = None) -> str:
    """Search for public or private channels in an Enterprise organization."""
    return _uc_request("GET", "/admin.conversations.search", query_params={"team_ids": team_ids, "query": query, "limit": limit, "cursor": cursor, "search_channel_types": search_channel_types, "sort": sort, "sort_dir": sort_dir})

@mcp.tool()
async def admin_conversations_setconversationprefs(token: dict, channel_id: dict, prefs: dict) -> str:
    """Set the posting permissions for a public or private channel."""
    return _uc_request("POST", "/admin.conversations.setConversationPrefs")

@mcp.tool()
async def admin_conversations_setteams(token: dict, channel_id: dict, team_id: dict | None = None, target_team_ids: dict | None = None, org_channel: dict | None = None) -> str:
    """Set the workspaces in an Enterprise grid org that connect to a public or private channel."""
    return _uc_request("POST", "/admin.conversations.setTeams")

@mcp.tool()
async def admin_conversations_unarchive(token: dict, channel_id: dict) -> str:
    """Unarchive a public or private channel."""
    return _uc_request("POST", "/admin.conversations.unarchive")

@mcp.tool()
async def admin_emoji_add(token: dict, name: dict, url: dict) -> str:
    """Add an emoji."""
    return _uc_request("POST", "/admin.emoji.add")

@mcp.tool()
async def admin_emoji_addalias(token: dict, name: dict, alias_for: dict) -> str:
    """Add an emoji alias."""
    return _uc_request("POST", "/admin.emoji.addAlias")

@mcp.tool()
async def admin_emoji_list(token: dict, cursor: dict | None = None, limit: dict | None = None) -> str:
    """List emoji for an Enterprise Grid organization."""
    return _uc_request("GET", "/admin.emoji.list", query_params={"token": token, "cursor": cursor, "limit": limit})

@mcp.tool()
async def admin_emoji_remove(token: dict, name: dict) -> str:
    """Remove an emoji across an Enterprise Grid organization"""
    return _uc_request("POST", "/admin.emoji.remove")

@mcp.tool()
async def admin_emoji_rename(token: dict, name: dict, new_name: dict) -> str:
    """Rename an emoji."""
    return _uc_request("POST", "/admin.emoji.rename")

@mcp.tool()
async def admin_inviterequests_approve(token: dict, invite_request_id: dict, team_id: dict | None = None) -> str:
    """Approve a workspace invite request."""
    return _uc_request("POST", "/admin.inviteRequests.approve")

@mcp.tool()
async def admin_inviterequests_approved_list(token: dict, team_id: dict | None = None, cursor: dict | None = None, limit: dict | None = None) -> str:
    """List all approved workspace invite requests."""
    return _uc_request("GET", "/admin.inviteRequests.approved.list", query_params={"team_id": team_id, "cursor": cursor, "limit": limit})

@mcp.tool()
async def admin_inviterequests_denied_list(token: dict, team_id: dict | None = None, cursor: dict | None = None, limit: dict | None = None) -> str:
    """List all denied workspace invite requests."""
    return _uc_request("GET", "/admin.inviteRequests.denied.list", query_params={"team_id": team_id, "cursor": cursor, "limit": limit})

@mcp.tool()
async def admin_inviterequests_deny(token: dict, invite_request_id: dict, team_id: dict | None = None) -> str:
    """Deny a workspace invite request."""
    return _uc_request("POST", "/admin.inviteRequests.deny")

@mcp.tool()
async def admin_inviterequests_list(token: dict, team_id: dict | None = None, cursor: dict | None = None, limit: dict | None = None) -> str:
    """List all pending workspace invite requests."""
    return _uc_request("GET", "/admin.inviteRequests.list", query_params={"team_id": team_id, "cursor": cursor, "limit": limit})

@mcp.tool()
async def admin_teams_admins_list(token: dict, team_id: dict, limit: dict | None = None, cursor: dict | None = None) -> str:
    """List all of the admins on a given workspace."""
    return _uc_request("GET", "/admin.teams.admins.list", query_params={"token": token, "limit": limit, "cursor": cursor, "team_id": team_id})

@mcp.tool()
async def admin_teams_create(token: dict, team_domain: dict, team_name: dict, team_description: dict | None = None, team_discoverability: dict | None = None) -> str:
    """Create an Enterprise team."""
    return _uc_request("POST", "/admin.teams.create")

@mcp.tool()
async def admin_teams_list(token: dict, limit: dict | None = None, cursor: dict | None = None) -> str:
    """List all teams on an Enterprise organization"""
    return _uc_request("GET", "/admin.teams.list", query_params={"limit": limit, "cursor": cursor})

@mcp.tool()
async def admin_teams_owners_list(token: dict, team_id: dict, limit: dict | None = None, cursor: dict | None = None) -> str:
    """List all of the owners on a given workspace."""
    return _uc_request("GET", "/admin.teams.owners.list", query_params={"token": token, "team_id": team_id, "limit": limit, "cursor": cursor})

@mcp.tool()
async def admin_teams_settings_info(token: dict, team_id: dict) -> str:
    """Fetch information about settings in a workspace"""
    return _uc_request("GET", "/admin.teams.settings.info", query_params={"team_id": team_id})

@mcp.tool()
async def admin_teams_settings_setdefaultchannels(token: dict, team_id: dict, channel_ids: dict) -> str:
    """Set the default channels of a workspace."""
    return _uc_request("POST", "/admin.teams.settings.setDefaultChannels")

@mcp.tool()
async def admin_teams_settings_setdescription(token: dict, team_id: dict, description: dict) -> str:
    """Set the description of a given workspace."""
    return _uc_request("POST", "/admin.teams.settings.setDescription")

@mcp.tool()
async def admin_teams_settings_setdiscoverability(token: dict, team_id: dict, discoverability: dict) -> str:
    """An API method that allows admins to set the discoverability of a given workspace"""
    return _uc_request("POST", "/admin.teams.settings.setDiscoverability")

@mcp.tool()
async def admin_teams_settings_seticon(token: dict, image_url: dict, team_id: dict) -> str:
    """Sets the icon of a workspace."""
    return _uc_request("POST", "/admin.teams.settings.setIcon")

@mcp.tool()
async def admin_teams_settings_setname(token: dict, team_id: dict, name: dict) -> str:
    """Set the name of a given workspace."""
    return _uc_request("POST", "/admin.teams.settings.setName")

@mcp.tool()
async def admin_usergroups_addchannels(token: dict, usergroup_id: dict, channel_ids: dict, team_id: dict | None = None) -> str:
    """Add one or more default channels to an IDP group."""
    return _uc_request("POST", "/admin.usergroups.addChannels")

@mcp.tool()
async def admin_usergroups_addteams(token: dict, usergroup_id: dict, team_ids: dict, auto_provision: dict | None = None) -> str:
    """Associate one or more default workspaces with an organization-wide IDP group."""
    return _uc_request("POST", "/admin.usergroups.addTeams")

@mcp.tool()
async def admin_usergroups_listchannels(token: dict, usergroup_id: dict, team_id: dict | None = None, include_num_members: dict | None = None) -> str:
    """List the channels linked to an org-level IDP group (user group)."""
    return _uc_request("GET", "/admin.usergroups.listChannels", query_params={"usergroup_id": usergroup_id, "team_id": team_id, "include_num_members": include_num_members})

@mcp.tool()
async def admin_usergroups_removechannels(token: dict, usergroup_id: dict, channel_ids: dict) -> str:
    """Remove one or more default channels from an org-level IDP group (user group)."""
    return _uc_request("POST", "/admin.usergroups.removeChannels")

@mcp.tool()
async def admin_users_assign(token: dict, team_id: dict, user_id: dict, is_restricted: dict | None = None, is_ultra_restricted: dict | None = None, channel_ids: dict | None = None) -> str:
    """Add an Enterprise user to a workspace."""
    return _uc_request("POST", "/admin.users.assign")

@mcp.tool()
async def admin_users_invite(token: dict, team_id: dict, email: dict, channel_ids: dict, custom_message: dict | None = None, real_name: dict | None = None, resend: dict | None = None, is_restricted: dict | None = None, is_ultra_restricted: dict | None = None, guest_expiration_ts: dict | None = None) -> str:
    """Invite a user to a workspace."""
    return _uc_request("POST", "/admin.users.invite")

@mcp.tool()
async def admin_users_list(token: dict, team_id: dict, cursor: dict | None = None, limit: dict | None = None) -> str:
    """List users on a workspace"""
    return _uc_request("GET", "/admin.users.list", query_params={"team_id": team_id, "cursor": cursor, "limit": limit})

@mcp.tool()
async def admin_users_remove(token: dict, team_id: dict, user_id: dict) -> str:
    """Remove a user from a workspace."""
    return _uc_request("POST", "/admin.users.remove")

@mcp.tool()
async def admin_users_session_invalidate(token: dict, team_id: dict, session_id: dict) -> str:
    """Invalidate a single session for a user by session_id"""
    return _uc_request("POST", "/admin.users.session.invalidate")

@mcp.tool()
async def admin_users_session_reset(token: dict, user_id: dict, mobile_only: dict | None = None, web_only: dict | None = None) -> str:
    """Wipes all valid sessions on all devices for a given user"""
    return _uc_request("POST", "/admin.users.session.reset")

@mcp.tool()
async def admin_users_setadmin(token: dict, team_id: dict, user_id: dict) -> str:
    """Set an existing guest, regular user, or owner to be an admin user."""
    return _uc_request("POST", "/admin.users.setAdmin")

@mcp.tool()
async def admin_users_setexpiration(token: dict, team_id: dict, user_id: dict, expiration_ts: dict) -> str:
    """Set an expiration for a guest user"""
    return _uc_request("POST", "/admin.users.setExpiration")

@mcp.tool()
async def admin_users_setowner(token: dict, team_id: dict, user_id: dict) -> str:
    """Set an existing guest, regular user, or admin user to be a workspace owner."""
    return _uc_request("POST", "/admin.users.setOwner")

@mcp.tool()
async def admin_users_setregular(token: dict, team_id: dict, user_id: dict) -> str:
    """Set an existing guest user, admin user, or owner to be a regular user."""
    return _uc_request("POST", "/admin.users.setRegular")

@mcp.tool()
async def api_test(error: dict | None = None, foo: dict | None = None) -> str:
    """Checks API calling code."""
    return _uc_request("GET", "/api.test", query_params={"error": error, "foo": foo})

@mcp.tool()
async def apps_event_authorizations_list(token: dict, event_context: dict, cursor: dict | None = None, limit: dict | None = None) -> str:
    """Get a list of authorizations for the given event context. Each authorization represents an app installation that the event is visible to."""
    return _uc_request("GET", "/apps.event.authorizations.list", query_params={"event_context": event_context, "cursor": cursor, "limit": limit})

@mcp.tool()
async def apps_permissions_info(token: dict | None = None) -> str:
    """Returns list of permissions this app has on a team."""
    return _uc_request("GET", "/apps.permissions.info", query_params={"token": token})

@mcp.tool()
async def apps_permissions_request(token: dict, scopes: dict, trigger_id: dict) -> str:
    """Allows an app to request additional scopes"""
    return _uc_request("GET", "/apps.permissions.request", query_params={"token": token, "scopes": scopes, "trigger_id": trigger_id})

@mcp.tool()
async def apps_permissions_resources_list(token: dict, cursor: dict | None = None, limit: dict | None = None) -> str:
    """Returns list of resource grants this app has on a team."""
    return _uc_request("GET", "/apps.permissions.resources.list", query_params={"token": token, "cursor": cursor, "limit": limit})

@mcp.tool()
async def apps_permissions_scopes_list(token: dict) -> str:
    """Returns list of scopes this app has on a team."""
    return _uc_request("GET", "/apps.permissions.scopes.list", query_params={"token": token})

@mcp.tool()
async def apps_permissions_users_list(token: dict, cursor: dict | None = None, limit: dict | None = None) -> str:
    """Returns list of user grants and corresponding scopes this app has on a team."""
    return _uc_request("GET", "/apps.permissions.users.list", query_params={"token": token, "cursor": cursor, "limit": limit})

@mcp.tool()
async def apps_permissions_users_request(token: dict, scopes: dict, trigger_id: dict, user: dict) -> str:
    """Enables an app to trigger a permissions modal to grant an app access to a user access scope."""
    return _uc_request("GET", "/apps.permissions.users.request", query_params={"token": token, "scopes": scopes, "trigger_id": trigger_id, "user": user})

@mcp.tool()
async def apps_uninstall(token: dict | None = None, client_id: dict | None = None, client_secret: dict | None = None) -> str:
    """Uninstalls your app from a workspace."""
    return _uc_request("GET", "/apps.uninstall", query_params={"token": token, "client_id": client_id, "client_secret": client_secret})

@mcp.tool()
async def auth_revoke(token: dict, test: dict | None = None) -> str:
    """Revokes a token."""
    return _uc_request("GET", "/auth.revoke", query_params={"token": token, "test": test})

@mcp.tool()
async def auth_test(token: dict) -> str:
    """Checks authentication & identity."""
    return _uc_request("GET", "/auth.test")

@mcp.tool()
async def bots_info(token: dict, bot: dict | None = None) -> str:
    """Gets information about a bot user."""
    return _uc_request("GET", "/bots.info", query_params={"token": token, "bot": bot})

@mcp.tool()
async def calls_add(token: dict, external_unique_id: dict, join_url: dict, external_display_id: dict | None = None, desktop_app_join_url: dict | None = None, date_start: dict | None = None, title: dict | None = None, created_by: dict | None = None, users: dict | None = None) -> str:
    """Registers a new Call."""
    return _uc_request("POST", "/calls.add")

@mcp.tool()
async def calls_end(token: dict, id: dict, duration: dict | None = None) -> str:
    """Ends a Call."""
    return _uc_request("POST", "/calls.end")

@mcp.tool()
async def calls_info(token: dict, id: dict) -> str:
    """Returns information about a Call."""
    return _uc_request("GET", "/calls.info", query_params={"id": id})

@mcp.tool()
async def calls_participants_add(token: dict, id: dict, users: dict) -> str:
    """Registers new participants added to a Call."""
    return _uc_request("POST", "/calls.participants.add")

@mcp.tool()
async def calls_participants_remove(token: dict, id: dict, users: dict) -> str:
    """Registers participants removed from a Call."""
    return _uc_request("POST", "/calls.participants.remove")

@mcp.tool()
async def calls_update(token: dict, id: dict, title: dict | None = None, join_url: dict | None = None, desktop_app_join_url: dict | None = None) -> str:
    """Updates information about a Call."""
    return _uc_request("POST", "/calls.update")

@mcp.tool()
async def chat_delete(token: dict | None = None, ts: dict | None = None, channel: dict | None = None, as_user: dict | None = None) -> str:
    """Deletes a message."""
    return _uc_request("POST", "/chat.delete")

@mcp.tool()
async def chat_deletescheduledmessage(token: dict, channel: dict, scheduled_message_id: dict, as_user: dict | None = None) -> str:
    """Deletes a pending scheduled message from the queue."""
    return _uc_request("POST", "/chat.deleteScheduledMessage")

@mcp.tool()
async def chat_getpermalink(token: dict, channel: dict, message_ts: dict) -> str:
    """Retrieve a permalink URL for a specific extant message"""
    return _uc_request("GET", "/chat.getPermalink", query_params={"token": token, "channel": channel, "message_ts": message_ts})

@mcp.tool()
async def chat_memessage(token: dict | None = None, channel: dict | None = None, text: dict | None = None) -> str:
    """Share a me message into a channel."""
    return _uc_request("POST", "/chat.meMessage")

@mcp.tool()
async def chat_postephemeral(token: dict, channel: dict, user: dict, as_user: dict | None = None, attachments: dict | None = None, blocks: dict | None = None, icon_emoji: dict | None = None, icon_url: dict | None = None, link_names: dict | None = None, parse: dict | None = None, text: dict | None = None, thread_ts: dict | None = None, username: dict | None = None) -> str:
    """Sends an ephemeral message to a user in a channel."""
    return _uc_request("POST", "/chat.postEphemeral")

@mcp.tool()
async def chat_postmessage(token: dict, channel: dict, as_user: dict | None = None, attachments: dict | None = None, blocks: dict | None = None, icon_emoji: dict | None = None, icon_url: dict | None = None, link_names: dict | None = None, mrkdwn: dict | None = None, parse: dict | None = None, reply_broadcast: dict | None = None, text: dict | None = None, thread_ts: dict | None = None, unfurl_links: dict | None = None, unfurl_media: dict | None = None, username: dict | None = None) -> str:
    """Sends a message to a channel."""
    return _uc_request("POST", "/chat.postMessage")

@mcp.tool()
async def chat_schedulemessage(token: dict | None = None, channel: dict | None = None, text: dict | None = None, post_at: dict | None = None, parse: dict | None = None, as_user: dict | None = None, link_names: dict | None = None, attachments: dict | None = None, blocks: dict | None = None, unfurl_links: dict | None = None, unfurl_media: dict | None = None, thread_ts: dict | None = None, reply_broadcast: dict | None = None) -> str:
    """Schedules a message to be sent to a channel."""
    return _uc_request("POST", "/chat.scheduleMessage")

@mcp.tool()
async def chat_scheduledmessages_list(token: dict | None = None, channel: dict | None = None, latest: dict | None = None, oldest: dict | None = None, limit: dict | None = None, cursor: dict | None = None) -> str:
    """Returns a list of scheduled messages."""
    return _uc_request("GET", "/chat.scheduledMessages.list", query_params={"channel": channel, "latest": latest, "oldest": oldest, "limit": limit, "cursor": cursor})

@mcp.tool()
async def chat_unfurl(token: dict, channel: dict, ts: dict, unfurls: dict | None = None, user_auth_message: dict | None = None, user_auth_required: dict | None = None, user_auth_url: dict | None = None) -> str:
    """Provide custom unfurl behavior for user-posted URLs"""
    return _uc_request("POST", "/chat.unfurl")

@mcp.tool()
async def chat_update(token: dict, channel: dict, ts: dict, as_user: dict | None = None, attachments: dict | None = None, blocks: dict | None = None, link_names: dict | None = None, parse: dict | None = None, text: dict | None = None) -> str:
    """Updates a message."""
    return _uc_request("POST", "/chat.update")

@mcp.tool()
async def conversations_archive(token: dict | None = None, channel: dict | None = None) -> str:
    """Archives a conversation."""
    return _uc_request("POST", "/conversations.archive")

@mcp.tool()
async def conversations_close(token: dict | None = None, channel: dict | None = None) -> str:
    """Closes a direct message or multi-person direct message."""
    return _uc_request("POST", "/conversations.close")

@mcp.tool()
async def conversations_create(token: dict | None = None, name: dict | None = None, is_private: dict | None = None) -> str:
    """Initiates a public or private channel-based conversation"""
    return _uc_request("POST", "/conversations.create")

@mcp.tool()
async def conversations_history(token: dict | None = None, channel: dict | None = None, latest: dict | None = None, oldest: dict | None = None, inclusive: dict | None = None, limit: dict | None = None, cursor: dict | None = None) -> str:
    """Fetches a conversation's history of messages and events."""
    return _uc_request("GET", "/conversations.history", query_params={"token": token, "channel": channel, "latest": latest, "oldest": oldest, "inclusive": inclusive, "limit": limit, "cursor": cursor})

@mcp.tool()
async def conversations_info(token: dict | None = None, channel: dict | None = None, include_locale: dict | None = None, include_num_members: dict | None = None) -> str:
    """Retrieve information about a conversation."""
    return _uc_request("GET", "/conversations.info", query_params={"token": token, "channel": channel, "include_locale": include_locale, "include_num_members": include_num_members})

@mcp.tool()
async def conversations_invite(token: dict | None = None, channel: dict | None = None, users: dict | None = None) -> str:
    """Invites users to a channel."""
    return _uc_request("POST", "/conversations.invite")

@mcp.tool()
async def conversations_join(token: dict | None = None, channel: dict | None = None) -> str:
    """Joins an existing conversation."""
    return _uc_request("POST", "/conversations.join")

@mcp.tool()
async def conversations_kick(token: dict | None = None, channel: dict | None = None, user: dict | None = None) -> str:
    """Removes a user from a conversation."""
    return _uc_request("POST", "/conversations.kick")

@mcp.tool()
async def conversations_leave(token: dict | None = None, channel: dict | None = None) -> str:
    """Leaves a conversation."""
    return _uc_request("POST", "/conversations.leave")

@mcp.tool()
async def conversations_list(token: dict | None = None, exclude_archived: dict | None = None, types: dict | None = None, limit: dict | None = None, cursor: dict | None = None) -> str:
    """Lists all channels in a Slack team."""
    return _uc_request("GET", "/conversations.list", query_params={"token": token, "exclude_archived": exclude_archived, "types": types, "limit": limit, "cursor": cursor})

@mcp.tool()
async def conversations_mark(token: dict | None = None, channel: dict | None = None, ts: dict | None = None) -> str:
    """Sets the read cursor in a channel."""
    return _uc_request("POST", "/conversations.mark")

@mcp.tool()
async def conversations_members(token: dict | None = None, channel: dict | None = None, limit: dict | None = None, cursor: dict | None = None) -> str:
    """Retrieve members of a conversation."""
    return _uc_request("GET", "/conversations.members", query_params={"token": token, "channel": channel, "limit": limit, "cursor": cursor})

@mcp.tool()
async def conversations_open(token: dict | None = None, channel: dict | None = None, users: dict | None = None, return_im: dict | None = None) -> str:
    """Opens or resumes a direct message or multi-person direct message."""
    return _uc_request("POST", "/conversations.open")

@mcp.tool()
async def conversations_rename(token: dict | None = None, channel: dict | None = None, name: dict | None = None) -> str:
    """Renames a conversation."""
    return _uc_request("POST", "/conversations.rename")

@mcp.tool()
async def conversations_replies(token: dict | None = None, channel: dict | None = None, ts: dict | None = None, latest: dict | None = None, oldest: dict | None = None, inclusive: dict | None = None, limit: dict | None = None, cursor: dict | None = None) -> str:
    """Retrieve a thread of messages posted to a conversation"""
    return _uc_request("GET", "/conversations.replies", query_params={"token": token, "channel": channel, "ts": ts, "latest": latest, "oldest": oldest, "inclusive": inclusive, "limit": limit, "cursor": cursor})

@mcp.tool()
async def conversations_setpurpose(token: dict | None = None, channel: dict | None = None, purpose: dict | None = None) -> str:
    """Sets the purpose for a conversation."""
    return _uc_request("POST", "/conversations.setPurpose")

@mcp.tool()
async def conversations_settopic(token: dict | None = None, channel: dict | None = None, topic: dict | None = None) -> str:
    """Sets the topic for a conversation."""
    return _uc_request("POST", "/conversations.setTopic")

@mcp.tool()
async def conversations_unarchive(token: dict | None = None, channel: dict | None = None) -> str:
    """Reverses conversation archival."""
    return _uc_request("POST", "/conversations.unarchive")

@mcp.tool()
async def dialog_open(token: dict, dialog: dict, trigger_id: dict) -> str:
    """Open a dialog with a user"""
    return _uc_request("GET", "/dialog.open", query_params={"dialog": dialog, "trigger_id": trigger_id})

@mcp.tool()
async def dnd_enddnd(token: dict) -> str:
    """Ends the current user's Do Not Disturb session immediately."""
    return _uc_request("POST", "/dnd.endDnd")

@mcp.tool()
async def dnd_endsnooze(token: dict) -> str:
    """Ends the current user's snooze mode immediately."""
    return _uc_request("POST", "/dnd.endSnooze")

@mcp.tool()
async def dnd_info(token: dict | None = None, user: dict | None = None) -> str:
    """Retrieves a user's current Do Not Disturb status."""
    return _uc_request("GET", "/dnd.info", query_params={"token": token, "user": user})

@mcp.tool()
async def dnd_setsnooze(token: dict, num_minutes: dict) -> str:
    """Turns on Do Not Disturb mode for the current user, or changes its duration."""
    return _uc_request("POST", "/dnd.setSnooze")

@mcp.tool()
async def dnd_teaminfo(token: dict | None = None, users: dict | None = None) -> str:
    """Retrieves the Do Not Disturb status for up to 50 users on a team."""
    return _uc_request("GET", "/dnd.teamInfo", query_params={"token": token, "users": users})

@mcp.tool()
async def emoji_list(token: dict) -> str:
    """Lists custom emoji for a team."""
    return _uc_request("GET", "/emoji.list", query_params={"token": token})

@mcp.tool()
async def files_comments_delete(token: dict | None = None, file: dict | None = None, id: dict | None = None) -> str:
    """Deletes an existing comment on a file."""
    return _uc_request("POST", "/files.comments.delete")

@mcp.tool()
async def files_delete(token: dict | None = None, file: dict | None = None) -> str:
    """Deletes a file."""
    return _uc_request("POST", "/files.delete")

@mcp.tool()
async def files_info(token: dict | None = None, file: dict | None = None, count: dict | None = None, page: dict | None = None, limit: dict | None = None, cursor: dict | None = None) -> str:
    """Gets information about a file."""
    return _uc_request("GET", "/files.info", query_params={"token": token, "file": file, "count": count, "page": page, "limit": limit, "cursor": cursor})

@mcp.tool()
async def files_list(token: dict | None = None, user: dict | None = None, channel: dict | None = None, ts_from: dict | None = None, ts_to: dict | None = None, types: dict | None = None, count: dict | None = None, page: dict | None = None, show_files_hidden_by_limit: dict | None = None) -> str:
    """List for a team, in a channel, or from a user with applied filters."""
    return _uc_request("GET", "/files.list", query_params={"token": token, "user": user, "channel": channel, "ts_from": ts_from, "ts_to": ts_to, "types": types, "count": count, "page": page, "show_files_hidden_by_limit": show_files_hidden_by_limit})

@mcp.tool()
async def files_remote_add(token: dict | None = None, external_id: dict | None = None, title: dict | None = None, filetype: dict | None = None, external_url: dict | None = None, preview_image: dict | None = None, indexable_file_contents: dict | None = None) -> str:
    """Adds a file from a remote service"""
    return _uc_request("POST", "/files.remote.add")

@mcp.tool()
async def files_remote_info(token: dict | None = None, file: dict | None = None, external_id: dict | None = None) -> str:
    """Retrieve information about a remote file added to Slack"""
    return _uc_request("GET", "/files.remote.info", query_params={"token": token, "file": file, "external_id": external_id})

@mcp.tool()
async def files_remote_list(token: dict | None = None, channel: dict | None = None, ts_from: dict | None = None, ts_to: dict | None = None, limit: dict | None = None, cursor: dict | None = None) -> str:
    """Retrieve information about a remote file added to Slack"""
    return _uc_request("GET", "/files.remote.list", query_params={"token": token, "channel": channel, "ts_from": ts_from, "ts_to": ts_to, "limit": limit, "cursor": cursor})

@mcp.tool()
async def files_remote_remove(token: dict | None = None, file: dict | None = None, external_id: dict | None = None) -> str:
    """Remove a remote file."""
    return _uc_request("POST", "/files.remote.remove")

@mcp.tool()
async def files_remote_share(token: dict | None = None, file: dict | None = None, external_id: dict | None = None, channels: dict | None = None) -> str:
    """Share a remote file into a channel."""
    return _uc_request("GET", "/files.remote.share", query_params={"token": token, "file": file, "external_id": external_id, "channels": channels})

@mcp.tool()
async def files_remote_update(token: dict | None = None, file: dict | None = None, external_id: dict | None = None, title: dict | None = None, filetype: dict | None = None, external_url: dict | None = None, preview_image: dict | None = None, indexable_file_contents: dict | None = None) -> str:
    """Updates an existing remote file."""
    return _uc_request("POST", "/files.remote.update")

@mcp.tool()
async def files_revokepublicurl(token: dict | None = None, file: dict | None = None) -> str:
    """Revokes public/external sharing access for a file"""
    return _uc_request("POST", "/files.revokePublicURL")

@mcp.tool()
async def files_sharedpublicurl(token: dict | None = None, file: dict | None = None) -> str:
    """Enables a file for public/external sharing."""
    return _uc_request("POST", "/files.sharedPublicURL")

@mcp.tool()
async def files_upload(token: dict | None = None, file: dict | None = None, content: dict | None = None, filetype: dict | None = None, filename: dict | None = None, title: dict | None = None, initial_comment: dict | None = None, channels: dict | None = None, thread_ts: dict | None = None) -> str:
    """Uploads or creates a file."""
    return _uc_request("POST", "/files.upload")

@mcp.tool()
async def migration_exchange(token: dict, users: dict, team_id: dict | None = None, to_old: dict | None = None) -> str:
    """For Enterprise Grid workspaces, map local user IDs to global user IDs"""
    return _uc_request("GET", "/migration.exchange", query_params={"token": token, "users": users, "team_id": team_id, "to_old": to_old})

@mcp.tool()
async def oauth_access(client_id: dict | None = None, client_secret: dict | None = None, code: dict | None = None, redirect_uri: dict | None = None, single_channel: dict | None = None) -> str:
    """Exchanges a temporary OAuth verifier code for an access token."""
    return _uc_request("GET", "/oauth.access", query_params={"client_id": client_id, "client_secret": client_secret, "code": code, "redirect_uri": redirect_uri, "single_channel": single_channel})

@mcp.tool()
async def oauth_token(client_id: dict | None = None, client_secret: dict | None = None, code: dict | None = None, redirect_uri: dict | None = None, single_channel: dict | None = None) -> str:
    """Exchanges a temporary OAuth verifier code for a workspace token."""
    return _uc_request("GET", "/oauth.token", query_params={"client_id": client_id, "client_secret": client_secret, "code": code, "redirect_uri": redirect_uri, "single_channel": single_channel})

@mcp.tool()
async def oauth_v2_access(code: dict, client_id: dict | None = None, client_secret: dict | None = None, redirect_uri: dict | None = None) -> str:
    """Exchanges a temporary OAuth verifier code for an access token."""
    return _uc_request("GET", "/oauth.v2.access", query_params={"client_id": client_id, "client_secret": client_secret, "code": code, "redirect_uri": redirect_uri})

@mcp.tool()
async def pins_add(token: dict, channel: dict, timestamp: dict | None = None) -> str:
    """Pins an item to a channel."""
    return _uc_request("POST", "/pins.add")

@mcp.tool()
async def pins_list(token: dict, channel: dict) -> str:
    """Lists items pinned to a channel."""
    return _uc_request("GET", "/pins.list", query_params={"token": token, "channel": channel})

@mcp.tool()
async def pins_remove(token: dict, channel: dict, timestamp: dict | None = None) -> str:
    """Un-pins an item from a channel."""
    return _uc_request("POST", "/pins.remove")

@mcp.tool()
async def reactions_add(channel: dict, name: dict, timestamp: dict, token: dict) -> str:
    """Adds a reaction to an item."""
    return _uc_request("POST", "/reactions.add")

@mcp.tool()
async def reactions_get(token: dict, channel: dict | None = None, file: dict | None = None, file_comment: dict | None = None, full: dict | None = None, timestamp: dict | None = None) -> str:
    """Gets reactions for an item."""
    return _uc_request("GET", "/reactions.get", query_params={"token": token, "channel": channel, "file": file, "file_comment": file_comment, "full": full, "timestamp": timestamp})

@mcp.tool()
async def reactions_list(token: dict, user: dict | None = None, full: dict | None = None, count: dict | None = None, page: dict | None = None, cursor: dict | None = None, limit: dict | None = None) -> str:
    """Lists reactions made by a user."""
    return _uc_request("GET", "/reactions.list", query_params={"token": token, "user": user, "full": full, "count": count, "page": page, "cursor": cursor, "limit": limit})

@mcp.tool()
async def reactions_remove(token: dict, name: dict, file: dict | None = None, file_comment: dict | None = None, channel: dict | None = None, timestamp: dict | None = None) -> str:
    """Removes a reaction from an item."""
    return _uc_request("POST", "/reactions.remove")

@mcp.tool()
async def reminders_add(token: dict, text: dict, time: dict, user: dict | None = None) -> str:
    """Creates a reminder."""
    return _uc_request("POST", "/reminders.add")

@mcp.tool()
async def reminders_complete(token: dict | None = None, reminder: dict | None = None) -> str:
    """Marks a reminder as complete."""
    return _uc_request("POST", "/reminders.complete")

@mcp.tool()
async def reminders_delete(token: dict | None = None, reminder: dict | None = None) -> str:
    """Deletes a reminder."""
    return _uc_request("POST", "/reminders.delete")

@mcp.tool()
async def reminders_info(token: dict | None = None, reminder: dict | None = None) -> str:
    """Gets information about a reminder."""
    return _uc_request("GET", "/reminders.info", query_params={"token": token, "reminder": reminder})

@mcp.tool()
async def reminders_list(token: dict | None = None) -> str:
    """Lists all reminders created by or for a given user."""
    return _uc_request("GET", "/reminders.list", query_params={"token": token})

@mcp.tool()
async def rtm_connect(token: dict, batch_presence_aware: dict | None = None, presence_sub: dict | None = None) -> str:
    """Starts a Real Time Messaging session."""
    return _uc_request("GET", "/rtm.connect", query_params={"token": token, "batch_presence_aware": batch_presence_aware, "presence_sub": presence_sub})

@mcp.tool()
async def search_messages(token: dict, query: dict, count: dict | None = None, highlight: dict | None = None, page: dict | None = None, sort: dict | None = None, sort_dir: dict | None = None) -> str:
    """Searches for messages matching a query."""
    return _uc_request("GET", "/search.messages", query_params={"token": token, "count": count, "highlight": highlight, "page": page, "query": query, "sort": sort, "sort_dir": sort_dir})

@mcp.tool()
async def stars_add(token: dict, channel: dict | None = None, file: dict | None = None, file_comment: dict | None = None, timestamp: dict | None = None) -> str:
    """Adds a star to an item."""
    return _uc_request("POST", "/stars.add")

@mcp.tool()
async def stars_list(token: dict | None = None, count: dict | None = None, page: dict | None = None, cursor: dict | None = None, limit: dict | None = None) -> str:
    """Lists stars for a user."""
    return _uc_request("GET", "/stars.list", query_params={"token": token, "count": count, "page": page, "cursor": cursor, "limit": limit})

@mcp.tool()
async def stars_remove(token: dict, channel: dict | None = None, file: dict | None = None, file_comment: dict | None = None, timestamp: dict | None = None) -> str:
    """Removes a star from an item."""
    return _uc_request("POST", "/stars.remove")

@mcp.tool()
async def team_accesslogs(token: dict, before: dict | None = None, count: dict | None = None, page: dict | None = None) -> str:
    """Gets the access logs for the current team."""
    return _uc_request("GET", "/team.accessLogs", query_params={"token": token, "before": before, "count": count, "page": page})

@mcp.tool()
async def team_billableinfo(token: dict, user: dict | None = None) -> str:
    """Gets billable users information for the current team."""
    return _uc_request("GET", "/team.billableInfo", query_params={"token": token, "user": user})

@mcp.tool()
async def team_info(token: dict, team: dict | None = None) -> str:
    """Gets information about the current team."""
    return _uc_request("GET", "/team.info", query_params={"token": token, "team": team})

@mcp.tool()
async def team_integrationlogs(token: dict, app_id: dict | None = None, change_type: dict | None = None, count: dict | None = None, page: dict | None = None, service_id: dict | None = None, user: dict | None = None) -> str:
    """Gets the integration logs for the current team."""
    return _uc_request("GET", "/team.integrationLogs", query_params={"token": token, "app_id": app_id, "change_type": change_type, "count": count, "page": page, "service_id": service_id, "user": user})

@mcp.tool()
async def team_profile_get(token: dict, visibility: dict | None = None) -> str:
    """Retrieve a team's profile."""
    return _uc_request("GET", "/team.profile.get", query_params={"token": token, "visibility": visibility})

@mcp.tool()
async def usergroups_create(token: dict, name: dict, channels: dict | None = None, description: dict | None = None, handle: dict | None = None, include_count: dict | None = None) -> str:
    """Create a User Group"""
    return _uc_request("POST", "/usergroups.create")

@mcp.tool()
async def usergroups_disable(token: dict, usergroup: dict, include_count: dict | None = None) -> str:
    """Disable an existing User Group"""
    return _uc_request("POST", "/usergroups.disable")

@mcp.tool()
async def usergroups_enable(token: dict, usergroup: dict, include_count: dict | None = None) -> str:
    """Enable a User Group"""
    return _uc_request("POST", "/usergroups.enable")

@mcp.tool()
async def usergroups_list(token: dict, include_users: dict | None = None, include_count: dict | None = None, include_disabled: dict | None = None) -> str:
    """List all User Groups for a team"""
    return _uc_request("GET", "/usergroups.list", query_params={"include_users": include_users, "token": token, "include_count": include_count, "include_disabled": include_disabled})

@mcp.tool()
async def usergroups_update(token: dict, usergroup: dict, handle: dict | None = None, description: dict | None = None, channels: dict | None = None, include_count: dict | None = None, name: dict | None = None) -> str:
    """Update an existing User Group"""
    return _uc_request("POST", "/usergroups.update")

@mcp.tool()
async def usergroups_users_list(token: dict, usergroup: dict, include_disabled: dict | None = None) -> str:
    """List all users in a User Group"""
    return _uc_request("GET", "/usergroups.users.list", query_params={"token": token, "include_disabled": include_disabled, "usergroup": usergroup})

@mcp.tool()
async def usergroups_users_update(token: dict, usergroup: dict, users: dict, include_count: dict | None = None) -> str:
    """Update the list of users for a User Group"""
    return _uc_request("POST", "/usergroups.users.update")

@mcp.tool()
async def users_conversations(token: dict | None = None, user: dict | None = None, types: dict | None = None, exclude_archived: dict | None = None, limit: dict | None = None, cursor: dict | None = None) -> str:
    """List conversations the calling user may access."""
    return _uc_request("GET", "/users.conversations", query_params={"token": token, "user": user, "types": types, "exclude_archived": exclude_archived, "limit": limit, "cursor": cursor})

@mcp.tool()
async def users_deletephoto(token: dict) -> str:
    """Delete the user profile photo"""
    return _uc_request("POST", "/users.deletePhoto")

@mcp.tool()
async def users_getpresence(token: dict, user: dict | None = None) -> str:
    """Gets user presence information."""
    return _uc_request("GET", "/users.getPresence", query_params={"token": token, "user": user})

@mcp.tool()
async def users_identity(token: dict | None = None) -> str:
    """Get a user's identity."""
    return _uc_request("GET", "/users.identity", query_params={"token": token})

@mcp.tool()
async def users_info(token: dict, include_locale: dict | None = None, user: dict | None = None) -> str:
    """Gets information about a user."""
    return _uc_request("GET", "/users.info", query_params={"token": token, "include_locale": include_locale, "user": user})

@mcp.tool()
async def users_list(token: dict | None = None, limit: dict | None = None, cursor: dict | None = None, include_locale: dict | None = None) -> str:
    """Lists all users in a Slack team."""
    return _uc_request("GET", "/users.list", query_params={"token": token, "limit": limit, "cursor": cursor, "include_locale": include_locale})

@mcp.tool()
async def users_lookupbyemail(token: dict, email: dict) -> str:
    """Find a user with an email address."""
    return _uc_request("GET", "/users.lookupByEmail", query_params={"token": token, "email": email})

@mcp.tool()
async def users_profile_get(token: dict, include_labels: dict | None = None, user: dict | None = None) -> str:
    """Retrieves a user's profile information."""
    return _uc_request("GET", "/users.profile.get", query_params={"token": token, "include_labels": include_labels, "user": user})

@mcp.tool()
async def users_profile_set(token: dict, name: dict | None = None, profile: dict | None = None, user: dict | None = None, value: dict | None = None) -> str:
    """Set the profile information for a user."""
    return _uc_request("POST", "/users.profile.set")

@mcp.tool()
async def users_setactive(token: dict) -> str:
    """Marked a user as active. Deprecated and non-functional."""
    return _uc_request("POST", "/users.setActive")

@mcp.tool()
async def users_setphoto(token: dict, crop_w: dict | None = None, crop_x: dict | None = None, crop_y: dict | None = None, image: dict | None = None) -> str:
    """Set the user profile photo"""
    return _uc_request("POST", "/users.setPhoto")

@mcp.tool()
async def users_setpresence(token: dict, presence: dict) -> str:
    """Manually sets user presence."""
    return _uc_request("POST", "/users.setPresence")

@mcp.tool()
async def views_open(token: dict, trigger_id: dict, view: dict) -> str:
    """Open a view for a user."""
    return _uc_request("GET", "/views.open", query_params={"trigger_id": trigger_id, "view": view})

@mcp.tool()
async def views_publish(token: dict, user_id: dict, view: dict, hash: dict | None = None) -> str:
    """Publish a static view for a User."""
    return _uc_request("GET", "/views.publish", query_params={"user_id": user_id, "view": view, "hash": hash})

@mcp.tool()
async def views_push(token: dict, trigger_id: dict, view: dict) -> str:
    """Push a view onto the stack of a root view."""
    return _uc_request("GET", "/views.push", query_params={"trigger_id": trigger_id, "view": view})

@mcp.tool()
async def views_update(token: dict, view_id: dict | None = None, external_id: dict | None = None, view: dict | None = None, hash: dict | None = None) -> str:
    """Update an existing view."""
    return _uc_request("GET", "/views.update", query_params={"view_id": view_id, "external_id": external_id, "view": view, "hash": hash})

@mcp.tool()
async def workflows_stepcompleted(token: dict, workflow_step_execute_id: dict, outputs: dict | None = None) -> str:
    """Indicate that an app's step in a workflow completed execution."""
    return _uc_request("GET", "/workflows.stepCompleted", query_params={"workflow_step_execute_id": workflow_step_execute_id, "outputs": outputs})

@mcp.tool()
async def workflows_stepfailed(token: dict, workflow_step_execute_id: dict, error: dict) -> str:
    """Indicate that an app's step in a workflow failed to execute."""
    return _uc_request("GET", "/workflows.stepFailed", query_params={"workflow_step_execute_id": workflow_step_execute_id, "error": error})

@mcp.tool()
async def workflows_updatestep(token: dict, workflow_step_edit_id: dict, inputs: dict | None = None, outputs: dict | None = None, step_name: dict | None = None, step_image_url: dict | None = None) -> str:
    """Update the configuration for a workflow extension step."""
    return _uc_request("GET", "/workflows.updateStep", query_params={"workflow_step_edit_id": workflow_step_edit_id, "inputs": inputs, "outputs": outputs, "step_name": step_name, "step_image_url": step_image_url})

if __name__ == "__main__":
    uvicorn.run(_create_app(), host="0.0.0.0", port=8000)
