# Generated by uc-mcp generate
# Spec: examples/slack-openapi.yaml
# Connection: slack

from __future__ import annotations

import contextvars
import json
import logging
import os
from typing import Optional

import uvicorn
from databricks.sdk import WorkspaceClient
from databricks.sdk.credentials_provider import ModelServingUserCredentials
from databricks.sdk.service.serving import ExternalFunctionRequestHttpMethod
from mcp.server.fastmcp import FastMCP
from mcp.server.streamable_http_manager import StreamableHTTPSessionManager
from starlette.applications import Starlette
from starlette.routing import Mount
import contextlib

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

mcp = FastMCP("slack")
CONNECTION_NAME = "slack"

_METHOD_MAP = {
    "GET": ExternalFunctionRequestHttpMethod.GET,
    "POST": ExternalFunctionRequestHttpMethod.POST,
    "PUT": ExternalFunctionRequestHttpMethod.PUT,
    "PATCH": ExternalFunctionRequestHttpMethod.PATCH,
    "DELETE": ExternalFunctionRequestHttpMethod.DELETE,
}


def _uc_request(
    method: str,
    path: str,
    *,
    body: dict | None = None,
    query_params: dict | None = None,
    _client: WorkspaceClient | None = None,
) -> str:
    client = _client or _get_workspace_client()
    resp = client.serving_endpoints.http_request(
        conn=CONNECTION_NAME,
        method=_METHOD_MAP[method],
        path=path,
        headers={},
        json=body or {},
        params=query_params or {},
    )
    return resp.text if hasattr(resp, "text") else str(resp)


# ── Per-user auth ─────────────────────────────────────────────────────────

_forwarded_token: contextvars.ContextVar[Optional[str]] = contextvars.ContextVar(
    "_forwarded_token", default=None
)


class _ForwardedTokenMiddleware:
    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] == "http":
            headers = dict(scope.get("headers", []))
            token = (headers.get(b"x-forwarded-access-token") or b"").decode() or None
            _forwarded_token.set(token)
        await self.app(scope, receive, send)


def _get_workspace_client() -> WorkspaceClient:
    token = _forwarded_token.get()
    if token:
        return WorkspaceClient(token=token, auth_type="pat")
    if os.environ.get("IS_IN_DATABRICKS_MODEL_SERVING_ENV"):
        return WorkspaceClient(credentials_strategy=ModelServingUserCredentials())
    return WorkspaceClient()


# ── Starlette app ─────────────────────────────────────────────────────────


def _create_app() -> Starlette:
    session_manager = StreamableHTTPSessionManager(
        app=mcp._mcp_server,
        stateless=True,
        json_response=True,
    )

    @contextlib.asynccontextmanager
    async def lifespan(app: Starlette):
        async with session_manager.run():
            yield

    app = Starlette(
        routes=[Mount("/mcp", app=session_manager.handle_request)],
        lifespan=lifespan,
    )
    return _ForwardedTokenMiddleware(app)


@mcp.tool()
async def auth_test(token: dict) -> str:
    """Checks authentication & identity."""
    return _uc_request("GET", "/auth.test")

@mcp.tool()
async def chat_delete(token: dict | None = None, ts: dict | None = None, channel: dict | None = None, as_user: dict | None = None) -> str:
    """Deletes a message."""
    return _uc_request("POST", "/chat.delete")

@mcp.tool()
async def chat_getpermalink(token: dict, channel: dict, message_ts: dict) -> str:
    """Retrieve a permalink URL for a specific extant message"""
    return _uc_request("GET", "/chat.getPermalink", query_params={"token": token, "channel": channel, "message_ts": message_ts})

@mcp.tool()
async def chat_postephemeral(token: dict, channel: dict, user: dict, as_user: dict | None = None, attachments: dict | None = None, blocks: dict | None = None, icon_emoji: dict | None = None, icon_url: dict | None = None, link_names: dict | None = None, parse: dict | None = None, text: dict | None = None, thread_ts: dict | None = None, username: dict | None = None) -> str:
    """Sends an ephemeral message to a user in a channel."""
    return _uc_request("POST", "/chat.postEphemeral")

@mcp.tool()
async def chat_postmessage(token: dict, channel: dict, as_user: dict | None = None, attachments: dict | None = None, blocks: dict | None = None, icon_emoji: dict | None = None, icon_url: dict | None = None, link_names: dict | None = None, mrkdwn: dict | None = None, parse: dict | None = None, reply_broadcast: dict | None = None, text: dict | None = None, thread_ts: dict | None = None, unfurl_links: dict | None = None, unfurl_media: dict | None = None, username: dict | None = None) -> str:
    """Sends a message to a channel."""
    return _uc_request("POST", "/chat.postMessage")

@mcp.tool()
async def chat_update(token: dict, channel: dict, ts: dict, as_user: dict | None = None, attachments: dict | None = None, blocks: dict | None = None, link_names: dict | None = None, parse: dict | None = None, text: dict | None = None) -> str:
    """Updates a message."""
    return _uc_request("POST", "/chat.update")

@mcp.tool()
async def conversations_history(token: dict | None = None, channel: dict | None = None, latest: dict | None = None, oldest: dict | None = None, inclusive: dict | None = None, limit: dict | None = None, cursor: dict | None = None) -> str:
    """Fetches a conversation's history of messages and events."""
    return _uc_request("GET", "/conversations.history", query_params={"token": token, "channel": channel, "latest": latest, "oldest": oldest, "inclusive": inclusive, "limit": limit, "cursor": cursor})

@mcp.tool()
async def conversations_info(token: dict | None = None, channel: dict | None = None, include_locale: dict | None = None, include_num_members: dict | None = None) -> str:
    """Retrieve information about a conversation."""
    return _uc_request("GET", "/conversations.info", query_params={"token": token, "channel": channel, "include_locale": include_locale, "include_num_members": include_num_members})

@mcp.tool()
async def conversations_join(token: dict | None = None, channel: dict | None = None) -> str:
    """Joins an existing conversation."""
    return _uc_request("POST", "/conversations.join")

@mcp.tool()
async def conversations_list(token: dict | None = None, exclude_archived: dict | None = None, types: dict | None = None, limit: dict | None = None, cursor: dict | None = None) -> str:
    """Lists all channels in a Slack team."""
    return _uc_request("GET", "/conversations.list", query_params={"token": token, "exclude_archived": exclude_archived, "types": types, "limit": limit, "cursor": cursor})

@mcp.tool()
async def conversations_members(token: dict | None = None, channel: dict | None = None, limit: dict | None = None, cursor: dict | None = None) -> str:
    """Retrieve members of a conversation."""
    return _uc_request("GET", "/conversations.members", query_params={"token": token, "channel": channel, "limit": limit, "cursor": cursor})

@mcp.tool()
async def conversations_replies(token: dict | None = None, channel: dict | None = None, ts: dict | None = None, latest: dict | None = None, oldest: dict | None = None, inclusive: dict | None = None, limit: dict | None = None, cursor: dict | None = None) -> str:
    """Retrieve a thread of messages posted to a conversation"""
    return _uc_request("GET", "/conversations.replies", query_params={"token": token, "channel": channel, "ts": ts, "latest": latest, "oldest": oldest, "inclusive": inclusive, "limit": limit, "cursor": cursor})

@mcp.tool()
async def files_info(token: dict | None = None, file: dict | None = None, count: dict | None = None, page: dict | None = None, limit: dict | None = None, cursor: dict | None = None) -> str:
    """Gets information about a file."""
    return _uc_request("GET", "/files.info", query_params={"token": token, "file": file, "count": count, "page": page, "limit": limit, "cursor": cursor})

@mcp.tool()
async def files_list(token: dict | None = None, user: dict | None = None, channel: dict | None = None, ts_from: dict | None = None, ts_to: dict | None = None, types: dict | None = None, count: dict | None = None, page: dict | None = None, show_files_hidden_by_limit: dict | None = None) -> str:
    """List for a team, in a channel, or from a user with applied filters."""
    return _uc_request("GET", "/files.list", query_params={"token": token, "user": user, "channel": channel, "ts_from": ts_from, "ts_to": ts_to, "types": types, "count": count, "page": page, "show_files_hidden_by_limit": show_files_hidden_by_limit})

@mcp.tool()
async def reactions_add(channel: dict, name: dict, timestamp: dict, token: dict) -> str:
    """Adds a reaction to an item."""
    return _uc_request("POST", "/reactions.add")

@mcp.tool()
async def reactions_get(token: dict, channel: dict | None = None, file: dict | None = None, file_comment: dict | None = None, full: dict | None = None, timestamp: dict | None = None) -> str:
    """Gets reactions for an item."""
    return _uc_request("GET", "/reactions.get", query_params={"token": token, "channel": channel, "file": file, "file_comment": file_comment, "full": full, "timestamp": timestamp})

@mcp.tool()
async def reactions_remove(token: dict, name: dict, file: dict | None = None, file_comment: dict | None = None, channel: dict | None = None, timestamp: dict | None = None) -> str:
    """Removes a reaction from an item."""
    return _uc_request("POST", "/reactions.remove")

@mcp.tool()
async def search_messages(token: dict, query: dict, count: dict | None = None, highlight: dict | None = None, page: dict | None = None, sort: dict | None = None, sort_dir: dict | None = None) -> str:
    """Searches for messages matching a query."""
    return _uc_request("GET", "/search.messages", query_params={"token": token, "count": count, "highlight": highlight, "page": page, "query": query, "sort": sort, "sort_dir": sort_dir})

@mcp.tool()
async def users_getpresence(token: dict, user: dict | None = None) -> str:
    """Gets user presence information."""
    return _uc_request("GET", "/users.getPresence", query_params={"token": token, "user": user})

@mcp.tool()
async def users_info(token: dict, include_locale: dict | None = None, user: dict | None = None) -> str:
    """Gets information about a user."""
    return _uc_request("GET", "/users.info", query_params={"token": token, "include_locale": include_locale, "user": user})

@mcp.tool()
async def users_list(token: dict | None = None, limit: dict | None = None, cursor: dict | None = None, include_locale: dict | None = None) -> str:
    """Lists all users in a Slack team."""
    return _uc_request("GET", "/users.list", query_params={"token": token, "limit": limit, "cursor": cursor, "include_locale": include_locale})

if __name__ == "__main__":
    uvicorn.run(_create_app(), host="0.0.0.0", port=8000)
